name: SpillNDrop
version: '0.1'
main: dev.gdlev.spillNDrop.SpillNDrop
api-version: '1.21'
authors: [ GDLev ]
description: Spill your inventory on impact! Items scatter when you fall, get rammed by a goat, or caught in a sonic boom. Configurable drop chances, water spills, potion smashing and more.

commands:
  spillndrop:
    description: Main command for SpillNDrop
    aliases: [snd]
    permission: spillndrop.admin

permissions:
  spillndrop.admin:
    description: Grants access to all SpillNDrop commands
    default: op
